name: Broken Links Checker

on: [push]
  # schedule:
  #   - cron:  '0 10 * * 1-5'

jobs:
  checkLinks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

    with:
      node-version: '12.x'

    - run: npm i broken-link-checker
    - run: node scripts/check-broken-links.js

  slackNotification:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: general
        SLACK_MESSAGE: Broken Link Checker report
        SLACK_TITLE: BLC REPORT
        SLACK_USERNAME: BLC
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}